version: "3.9"
services:
  discovery:
    image: vmware/vsan-prometheus-servicediscovery:beta-0.11
    env_file:
    - vars.env
    volumes:
    - /root/vsan-prometheus/vol:/vol
  prometheus:
    build: ./prometheus/.
    ports:
    - "9090:9090"
    volumes:
    - /root/vsan-prometheus/vol:/vol
