version: "3.9"
services:
  discovery:
    image: vmware/vsan-prometheus-servicediscovery:beta-0.11
    env_file:
    - vars.env
    volumes:
    - /root/vsan-prometheus/vol:/vol
  prometheus:
    build: ./prometheus/.
    ports:
    - "9090:9090"
    volumes:
    - /root/vsan-prometheus/vol:/vol
  grafana:
    image: grafana/grafana:7.5.4
    ports:
    - "3000:3000"
    volumes:
    - ./grafana:/etc/grafana/provisioning
